### ISSUE TITLE
E363: pattern uses more memory than 'maxmempattern'

### ISSUE THREAD

**Issue by mxstbr** [styled-components/vim-styled-components#28]
Getting this error when opening any (?) JS file:

<img width="1213" alt="screen shot 2017-09-01 at 8 43 21 am" src="https://user-images.githubusercontent.com/7525670/29958216-e5355be8-8ef1-11e7-8c2f-49f1bb5ec410.png">

These files don't even contain any styled components!

**Comment by fleischie** [comment]
Hi Max, every JS file? Yes, probably. 😑

The way this plugin works is by checking, whether something is required/imported from a supported API by searching for a specific regular expression on every javascript file. The default memory is 1000 bytes and the error message basically indicates, that the search has to keep more than 1000 bytes in memory to check, whether this is the case.

I will have to tweak the regular expression to be not as inclusive but at the same time inclusive enough to not let all the edge case import/require statements fall off.

Currently it checks for (assume `libraries` is the list of supported library names):
```regexp
import(.|\n)*from.*[libraries]
```

or

```regexp
require(.|\n)*'[libraries]
```

Or it's an unmatched parenthesis thing? Like in [this similar issue on vim-markdown](https://github.com/gabrielelana/vim-markdown/issues/4). I have to check, thanks for the notification. 😊

**Comment by mxstbr** [comment]
I feel like assuming that any `styled.div` call with a tagged template literal likely has styles after it is fine, why do we check for imports?

**Comment by fleischie** [comment]
I thought checking for imports is the smallest common denominator.

The plugin does not specifically highlights CSS rules in tagged template literals, but CSS rules in all template strings, if the import statement is present.

But now that you mention it, maybe it makes more sense to only inject CSS rules into tagged template literals? But then again, how to know whether it's only API-conform tagged template literals?

**Comment by mxstbr** [comment]
I think there's just three cases where they should be highlighted as CSS:

```JS
styled.x`

`

styled(X)`

`

Comp.extend`

`
```

**Comment by fleischie** [comment]
What about `css`, `injectGlobal`, etc.?

There already was a discussion about whether to whitelist the tagged templates and I wasn't really convinced. (See #21.)

Do you have a lot of plugins and/or give an example file, that displays the `maxmempattern` errors? So I can better test? Also what's your environment? Vim Version, OS, etc.

**Comment by fleischie** [comment]
@mxstbr If you are still interested in this issue, I discussed a complete rewrite of this plugin [in this comment on #21](https://github.com/styled-components/vim-styled-components/issues/21#issuecomment-330175614).

I hope that a complete rewrite will mitigate this memory pattern issue.

**Comment by fleischie** [comment]
Update: Please see whether #30 helps you with this error.

**Comment by omeid** [comment]
#30 solves the problem for me.

```
nvim --version
NVIM v0.2.2
```

**Comment by nerfologist** [comment]
I also run into this error when running various commands on a non-styled component .js file.

#30 solves the problem for me too.

**Comment by fleischie** [comment]
Next week I'll probably merge #30 after fixing some long-standing issues. Hopefully this should fix this for good for now.

**Comment by FernandoTorres** [comment]
I just solved this issue by adding:

```
set maxmempattern = 2000000
```

to my vimrc.

In my case the symptom was inserting a '[' char on a long markdown file (~4K lines).

Found the solution here:

https://www.zhihu.com/question/60367881

You can also check `:help maxmempattern`
