### ISSUE TITLE
Usage with 'typescript.jsx" filetype

### ISSUE THREAD

**Issue by vjsingh** [styled-components/vim-styled-components#43]
I can't get this plugin to work for my TSX files. I'm using this plugin: https://github.com/peitalin/vim-jsx-typescript

which suggests this way of handling filetypes:
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.jsx

If I do ":set filetype=typescript" in my TSX file, then I see the styled-components styling correctly.

I tried for a while but couldn't figure it out. Is there any way to add support for "typescript.jsx" filetype?

**Comment by fleischie** [comment]
Hi. :thinking:  I don't seem to be able to reproduce this.

Can you give me a minimal `.vimrc` and example file, that illustrate what the problem is? If I change the filetype to `typescript.tsx` only my JSX styling changes, but the actual styled components highlighting still work.

**Comment by vjsingh** [comment]
Sorry for the delay on this. It seems to be working now, I'm not really sure what happened. I'll reopen if I can reproduce it in the future. =)
