### ISSUE TITLE
Suggestion: use the conventional "master" branch instead of "main"

### ISSUE THREAD

**Issue by trevordmiller** [styled-components/vim-styled-components#45]
So that you can do this:

```
Plug 'styled-components/vim-styled-components'
```

Instead of:

```
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }
```

**Comment by trevordmiller** [comment]
Not a big deal though, I assume you had a good reason for doing this instead of using the normal `master` :)

**Comment by tbo** [comment]
@trevordmiller I think this is a valid issue. Having `main` instead of `master` is counterintuitive. I assume, that `main` was chosen by accident, since all other `styled-components` repositories use `master`.

I would like to see this be reopened.

**Comment by fleischie** [comment]
@tbo, @trevordmiller I disagree strongly with the default branch name, that `git` is using. It has social and cultural connotations, that I personally will not promote.

@trevordmiller I guess the original issue is more targeted towards `vim-plug`, that uses `master` as the default branch, see https://github.com/junegunn/vim-plug/issues/288 for more details on this. I don't think it's the task of the plugin-maintainer to make it work with specific plugin managers.
@tbo I don't see how a name can be intuitive or not, but I chose the branch name on purpose.
