### ISSUE TITLE
Incorrect indentation for media query blocks

### ISSUE THREAD

**Issue by apazzolini** [styled-components/vim-styled-components#47]
When inside a media query block, indentation does not work as expected. This is specifically related to the `@` sign on the line - if you remove it, indentation works properly.

![Example](https://cl.ly/1Q2T0d2i3n3G/Screen%20Recording%202018-08-05%20at%2011.23%20AM.gif)

Minimal vim config

```
call plug#begin('~/.vim/plugged')
Plug 'styled-components/vim-styled-components', { 'for': 'javascript', 'branch': 'main' }
call plug#end()

filetype plugin indent on
syntax enable
```

Thanks!

**Comment by fleischie** [comment]
Hello. Thanks for the issue.

Just a short question now, before I look into it the following week: Did you try to add a css definition? It should re-indent on `:` and `;` among others. It's possible, it doesn't know it should indent based on the ambiguity of the surrounding block.

Please try out adding some css and/or tagged template interpolation and tell me, whether it still misbehaves. Thank you. ✌️

**Comment by apazzolini** [comment]
Unfortunately, adding a CSS definition doesn't help - the indentation remains one level less than it should.

I've also tried vim's indent feature (`=`), and that continues to indent incorrectly, with definitions and without.

**Comment by fleischie** [comment]
@apazzolini Hi, could you check out the latest `develop` branch to see, whether it fixes the reported issue? Don't hesitate with follow-up questions/issues with this. :v:

**Comment by apazzolini** [comment]
@fleischie It's working much better! There's still a bit of weirdness when I also have delimitmate enabled, but I don't think that's an issue for this project - using `=` to indent the range outputs the expected result.

![](https://cl.ly/0T3a1t0n3h0T/Screen%20Recording%202018-08-09%20at%2009.42%20AM.gif)

Thank you!

**Comment by fleischie** [comment]
Cool, glad to hear.

If you think I should look into Delimitmate + styled-components, just open another issue. I may not be able to solve it completely, but you know.... The more eyes, the merrier the issues... now, wait. 😋
