### ISSUE TITLE
Upcoming styled-components v4 changes

### ISSUE THREAD

**Issue by probablyup** [styled-components/vim-styled-components#48]
Just a heads-up that we will be making some top-level API changes in v4 that may affect your library.

1) `injectGlobal` is being removed
2) `createGlobalStyle` is being added

`createGlobalStyle` can likely inherit any syntax highlighting rules you may have been using for `injectGlobal`, `styled.*` etc.

More info: https://github.com/styled-components/styled-components/pull/1867

**Comment by fleischie** [comment]
Done in release [v2.6](https://github.com/styled-components/vim-styled-components/releases/tag/v2.6).

Sorry I forgot all about this in advance and only now saw a release-tweet, so I quickly added support for the keyword. 🙇
