### ISSUE TITLE
Syntax Highlighting Not Showing Up

### ISSUE THREAD

**Issue by mulholio** [styled-components/vim-styled-components#52]
I can't seem to get the highlighting working and styled components are just showing up as regular template literals:

![screenshot 2018-11-02 at 10 05 53](https://user-images.githubusercontent.com/20966690/47909127-e85a0e00-de86-11e8-8e9c-b6438773fcc2.png)

I apologise for the vague issue, but I can't think of any other relevant details. I am using neovim (although I saw that hadn't been an issue for other users).

You can find my .vimrc here: https://github.com/mulholio/dot-files/blob/master/vim/.vimrc

**Comment by mulholio** [comment]
I have disabled coloresque, indentLine, delimitMate and vim-polygot and none of them seem to be causing the issue.

**Comment by fleischie** [comment]
Hey @mulholio

I saw your issue and I will check it out as soon as I can.

I glimpsed, that you used `yats` is the above example a typescript file? Just so I know what to look for?

**Comment by fleischie** [comment]
Hey @mulholio again.

Could you please elaborate why you are using [sheerun/vim-polyglot](https://github.com/sheerun/vim-polyglot) as well as [othree/yajs.vim](https://github.com/othree/yajs.vim)?

I have to admit, this plugin was exclusively written using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) respectively vim-polyglot (which uses the former). Thus it makes sense that using different syntax highlighting plugins are not supported out of the box, yet.

I might be able to support other javascript syntax highlighting plugins, but this unfortunately takes time and effort. So there is no easy quickfix for you that I could recommend right now besides disabling the `yajs` plugin.

Again, I'd appreciate a short description of what made you use `yajs` so maybe I get an incentive to look at it.

**Comment by fleischie** [comment]
@mulholio I can take a look at [othree/yajs.vim](https://github.com/othree/yajs.vim), as there might be others that prefer it over [sheerun/vim-polyglot](https://github.com/sheerun/vim-polyglot) or thus [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript).

I keep you updated on the progress.

**Comment by fleischie** [comment]
@mulholio I now took a few hours to look at how [othree/yajs](https://github.com/othree/yajs.vim) classifies the base javascript syntax items to hook into it/extend it/operate on it. If you could check out the develop-branch I'd appreciate some feedback. :smile:

If you don't know how, it's:

`Plug 'styled-components/vim-styled-components', { 'branch': 'develop' }`

in your vimrc file where you would normally do `{ 'branch': 'main' }`.

**Comment by mulholio** [comment]
Thank you for the speedy response!

Still appears to be reluctant to highlight. 
<img width="617" alt="screenshot 2018-11-26 at 14 47 30" src="https://user-images.githubusercontent.com/20966690/49021298-3b736800-f18a-11e8-961a-96061c5e8feb.png">

It appears to have done something as my `const`s are now a different colour, but this doesn't seem to be affecting the styled components highlighting

**Comment by fleischie** [comment]
@mulholio Hmm... I have to admit I merely switched out `sheerun/polyglot` with `othree/yajs.vim` in my personal `.vimrc`. I will check out your `.vimrc` directly tomorrow, and see whether I can reproduce your results with it.

**Comment by mulholio** [comment]
Hopefully, it's not some other random plugin causing the issue.

Thank you once again.

**Comment by fleischie** [comment]
@mulholio I checkout out your vimrc from above, did change to `{ 'branch': 'develop' }` and then `:PlugInstall` (I saw that you use [junegunn/vim-plug](https://github.com/junegunn/vim-plug).

It did not actually show the branch, so either run `:PlugUpdate` (this seems to update the branch, if it changed in the vimrc) or remove the line, run `:PlugClean` and add it again.

Let me know, if this changes anything.

NOTE: A "clean" install with `{ 'branch': 'develop' }` (i.e. no previous `plugged` directory) works like a charm.

**Comment by mulholio** [comment]
Badabing! Working now.

I had previously called `:PlugUpdate` which I assumed updated to the correct branch. Might have only updated the main branch though as this didn't seem to fix the issue.

Commenting out the plugin completely, calling `:PlugClean`, then `:PlugInstall` got things working for me.
