### ISSUE TITLE
css right hand side value only not working

### ISSUE THREAD

**Issue by adrianhelvik** [styled-components/vim-styled-components#53]
This messes up the syntax highlighting beyond the template 

```
const sideOffset = css`calc(${circleDiameter} / 2 - ${lineWidth} / 2)`
```

Thanks :)

**Comment by adrianhelvik** [comment]
And it does not really matter that this css fragment isn't well highlighted. But it shouldn't mess up the highlighting beyond the template tag.

**Comment by adrianhelvik** [comment]
The syntax after the template tag is closed is `hi<cssCustomPositioningPrefix> trans<cssCustomPositioningPrefix lo<StorageClass>`.

**Comment by fleischie** [comment]
Hello and thanks for your effort @adrianhelvik .

Unfortunately I don't understand what you are trying to say or inquire with your issue. Please provide a short description of what you see (a screenshot works best) and ideally a minimal vimrc I can use to troubleshoot your issue.

And if you want to get an A+ on effort, consolidate your additional comments into one cohesive issue description. I really want to help but have the attention span of a gold fish. 😉

**Comment by adrianhelvik** [comment]
I did a PlugInstall and the problem was fixed. :)
