### ISSUE TITLE
Improve indenting for filetype `typescript.tsx`

### ISSUE THREAD

**Issue by fleischie** [styled-components/vim-styled-components#62]
The indenting in non-styled sections is not working, especially when in tsx sections:

Current behavior:

![Screen Shot 2019-06-07 at 14 31 19](https://user-images.githubusercontent.com/2211050/59104145-09a93e00-8931-11e9-8bb7-4b26d8a3833f.png)

Somwhat desired behavior:

![Screen Shot 2019-06-07 at 14 31 40](https://user-images.githubusercontent.com/2211050/59104161-14fc6980-8931-11e9-9e63-c53e98dcb504.png)

**Comment by sheerun** [comment]
The fix should look something like this to also account for vim-jsx-pretty plugin:

```
if &filetype =~ '^typescript' && exists('*GetTsxIndent')
  let s:JsIndentFunction = function('GetTsxIndent')
elseif &filetype =~ '^typescript' && exists('*GetTypescriptIndent')
  let s:JsIndentFunction = function('GetTypescriptIndent')
elseif exists('*GetJsxIndent')
  let s:JsIndentFunction = function('GetJsxIndent')
elseif exists('*GetJavascriptIndent')
  let s:JsIndentFunction = function('GetJavascriptIndent')
elseif exists('*GetJsIndent')
  let s:JsIndentFunction = function('GetJsIndent')
end
```

**Comment by fleischie** [comment]
Oh hey, thanks @sheerun for the hint. I might try it out whenever I feel like I can spare the moment. 🙇👍

**Comment by Ironimus** [comment]
I believe the issue is fixed and can be closed?

**Comment by Jayphen** [comment]
@sheerun Where should one put the above if/else block in order to fix this?
