### ISSUE TITLE
Breaking syntax highlighting with vim-javascript

### ISSUE THREAD

**Issue by mcmillion** [styled-components/vim-styled-components#64]
Not sure when this started happening (I've been using this plugin alongside vim-javascript for a while), but in a recent update, this plugin starts to break vanilla JS highlighting when scrolling:

<img width="155" alt="Screen Shot 2019-06-18 at 10 05 20 PM" src="https://user-images.githubusercontent.com/717799/59734661-f2632e00-9217-11e9-9562-dc8c2243c0a3.png">

Note that this is in a .js file with just javascript as the filetype. This is with only vim-javascript and vim-styled-components enabled. Doesn't matter if I enable vim-jsx-pretty or not.

**Comment by fleischie** [comment]
Hello. Thanks for reporting.

I suspect you are viewing a rather long file. Vim has a limit to how many lines it can "remember" to initialize a syntax block and keep highlighting. If it exceeds this limit it usually just drops the highlighting. (I sometimes get this is git commit patches).

There is another open issue that makes me re-evaluate the current setup (especially regarding typescript). Maybe if I find the time I can split the definitions of typescript and javascript, which would significantly reduce the effort to highlight javascript files, and maybe thus fixes this particular misbehavior.

Can you possibly share some more insights into the file you are watching? Is that a large JSON object? How many lines does the file have? Is there anything specific to the data that might cause a syntax issue (e.g. jsx or base64 in data, etc.). As much as you are able/comfortable to disclose, of course, would help.

🙇

**Comment by mcmillion** [comment]
So the file is _decently_ long (270ish lines), so that could be part of it, but it does render fine with the styled-components plugin turned off. It's just a vanilla JS file that exports an object. What's weird is I don't remember seeing this issue on any files in my project until a week or so ago. I'm starting to wonder if this is because of a recent neovim update.

**Comment by mcmillion** [comment]
<img width="251" alt="Screen Shot 2019-06-19 at 8 07 55 AM" src="https://user-images.githubusercontent.com/717799/59768110-5eba4d80-9269-11e9-8c3a-2111d5a36a2c.png">

<img width="288" alt="Screen Shot 2019-06-19 at 8 10 24 AM" src="https://user-images.githubusercontent.com/717799/59768284-b9ec4000-9269-11e9-9eb3-e9bdb0db64dd.png">

Here's another shot of it in another colorscheme. What's weird is that it's only affecting _some_ of the syntax highlighting (e.g. the string values in that screenshot are correct, but the keys are not)

It's also triggering the bracket matching to think that it's not closed, which feels like a hint, but I don't know near enough about how vim/neovim syntax highlighting works to know why.

**Comment by mcmillion** [comment]
<img width="256" alt="Screen Shot 2019-06-19 at 8 12 43 AM" src="https://user-images.githubusercontent.com/717799/59768468-09327080-926a-11e9-8bd4-bdd46d6429be.png">

Just saw this in another file (it's only 100 lines). The syntax highlighting doesn't shift colors when scrolling like the other one does, but the same highlighting weirdness is there on the closing braces.

**Comment by lynndylanhurley** [comment]
I'm seeing this as well.

Highlighting breaks following backticks (`), but works intermittently as I scroll through the files.

I don't see the issue when I disable the `styled-components` plugin.

**Comment by fr3fou** [comment]
I really need to find a solution to this. `vim-styled-components` is the only thing left from me finishing my nvim config :/

**Comment by fleischie** [comment]
@mcmillion @lynndylanhurley @fr3fou Can you do me a favor and type `:syntax sync fromstart` and see if that changes anything?

What I suspect is happening is that the syntax elements are more than the syncing needs to correctly highlight complex/long files. Setting the syncing to `fromstart` means it's caching **all** the lines in the file, which makes the syntax highlighting take longer but should be more correct.

<details>
Syntax synchronizing is the mechanism vim uses to know how to redraw the state of the currently shown contents, see `:help syn-sync` for more information.
</details>

**Comment by pbondoer** [comment]
@fleischie I was experiencing the same issue, `:syntax sync fromstart` fixes the issue for me.

**Comment by fr3fou** [comment]
That worked! Thanks!!

**Comment by lynndylanhurley** [comment]
I added this to my `.vimrc` and it seems to have fixed the issue:

```
autocmd BufEnter * :syntax sync fromstart
```

**Comment by fleischie** [comment]
I personally would advise against putting `:syn sync fromstart` in a general location for a general type (because it can slow down vim).

Especially as this plugin is mostly for javascript/typescript files.

So, if anything use `autocmd BufEnter *.{js,ts,jsx,tsx} :syntax sync fromstart` (and maybe `autocmd BufLeave *.{js,ts,jsx,tsx} :syntax sync clear` (this should reset all syntax sync settings, but beware that this overwrites any additional settings that might have happened, ymmv).

**Comment by fleischie** [comment]
I will add a short description to the README.md outlining this issue and how to circumvent it.
