### ISSUE TITLE
Highlighting breaks when calling styled from inside object

### ISSUE THREAD

**Issue by geocool** [styled-components/vim-styled-components#66]
Unfortunately, highlighting is not working with our code.

![Image of broken code](https://i.imgur.com/lhAfp7s.png)

**Comment by fleischie** [comment]
Hey @geocool , thanks for reporting this issue :pray: (and sorry for not responding until now),

can you please check out the latest `develop` branch, I implemented a solution that works as far as I can tell. Let me know if you need additional help (or e.g. the issue still exists). :+1:

**Comment by geocool** [comment]
Thanks @fleischie now it works 👍
