### ISSUE TITLE
Causes conflicts with vim-jsx-pretty: cannot disable on tsx

### ISSUE THREAD

**Issue by pappasam** [styled-components/vim-styled-components#76]
See https://github.com/MaxMEllon/vim-jsx-pretty/issues/124

Basically, `syntax/typescript.vim` automatically loads `syntax/javascript.vim`, preventing the configuration option `g:vim_jsx_pretty_disable_tsx` from working. I've stopped relying on this plugin, but since vim-jsx-pretty is a popular library, it might be a good idea to fix this issue at some point.

**Comment by stevematney** [comment]
This _should_ be resolved on the `develop` branch.

**Comment by CallumHoward** [comment]
This was working fine for me up until a few weeks ago and now with vim-jsx-pretty and vim-styled-components. 
- Now if I source vim-styled-components first I get errors and the styled components syntax highlighting doesn't work. 
- If I source it after vim-jsx-pretty there are no errors but still no syntax highlighting on styled components.
